# Generated by Django 5.2.7 on 2025-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='📷 Görsel oranı 16:9 olmalıdır (örnek: 1600x900, 1920x1080).', null=True, upload_to='event_images/'),
        ),
    ]
