# Generated by Django 5.2.7 on 2025-11-15 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='📷 Görsel oranı 16:9 olmalıdır (örnek: 1600x900, 1920x1080).', max_length=255, null=True, verbose_name='image'),
        ),
    ]
