# Generated by Django 5.2.7 on 2025-12-15 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_options_teammember_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
