# Generated by Django 5.2.7 on 2025-12-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammember_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='created_at',
        ),
    ]
