# Generated by Django 5.2.7 on 2025-11-15 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Lütfen 600x400 piksel boyutlarında bir logo yükleyin.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
