# Generated by Django 5.2.7 on 2025-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, help_text="📷 Firebase görsel URL'si", null=True),
        ),
    ]
