# Generated by Django 5.2.7 on 2025-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Görsel en boy oranı 16:9 olmalıdır (örnek: 1600x900, 1920x1080).', null=True, upload_to=''),
        ),
    ]
