# Generated by Django 5.2.7 on 2025-11-15 09:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Görsel en boy oranı 16:9 olmalıdır.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
