# Generated by Django 5.2.7 on 2025-11-15 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_options_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='📷 Görsel en boy oranı 16:9 olmalıdır (örnek: 1600x900, 1920x1080).', max_length=255, null=True, verbose_name='image'),
        ),
    ]
