# Generated by Django 5.2.7 on 2025-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_link', models.URLField(default='https://forms.gle/2wdBxZvqEaDv6ehZ7')),
            ],
        ),
    ]
