# Generated by Django 5.2.7 on 2025-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='Üye Ol Linki')),
            ],
            options={
                'verbose_name': 'Üye Ol Linki',
                'verbose_name_plural': 'Üye Ol Linki',
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
