# Generated by Django 5.2.7 on 2025-10-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_joinlink_delete_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinlink',
            options={},
        ),
        migrations.RenameField(
            model_name='joinlink',
            old_name='link',
            new_name='url',
        ),
    ]
