# Generated by Django 5.2.7 on 2025-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_joinlink_options_rename_link_joinlink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_link', models.URLField(blank=True, null=True, verbose_name='Hemen Üye Ol Linki')),
            ],
            options={
                'verbose_name': 'Ayar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.DeleteModel(
            name='JoinLink',
        ),
    ]
