# Generated by Django 5.2.7 on 2025-11-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_settings_delete_joinlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArsivEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='arsiv_photos/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Arşiv Girişi',
                'verbose_name_plural': 'Arşiv Girişleri',
            },
        ),
    ]
