# Generated by Django 5.2.7 on 2025-11-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_arsiventry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsiventry',
            name='photo',
            field=models.ImageField(blank=True, help_text='📷 Görsel oranı 16:9 olmalıdır (örnek: 1600x900, 1920x1080).', null=True, upload_to='blog_images/'),
        ),
    ]
