# Generated by Django 5.2.7 on 2025-11-02 12:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_arsiventry_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsiventry',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
