# Generated by Django 5.2.7 on 2025-11-15 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_arsiventry_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsiventry',
            options={'ordering': ['year'], 'verbose_name': 'Arşiv Girişi', 'verbose_name_plural': 'Arşiv Girişleri'},
        ),
        migrations.AlterField(
            model_name='arsiventry',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='📷 Görsel oranı 16:9 olmalıdır (örnek: 1600x900, 1920x1080).', max_length=255, null=True, verbose_name='image'),
        ),
    ]
