# Generated by Django 5.2.7 on 2025-11-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_arsiventry_options_alter_arsiventry_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsiventry',
            options={'ordering': ['-id'], 'verbose_name': 'Arşiv Girişi', 'verbose_name_plural': 'Arşiv Girişleri'},
        ),
    ]
