# Generated by Django 5.2.7 on 2025-11-15 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_arsiventry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsiventry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Arşiv Girişi', 'verbose_name_plural': 'Arşiv Girişleri'},
        ),
        migrations.AddField(
            model_name='arsiventry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
